export const GENRE_SYNONYMS: Record<string, string> = {
  action: "Action",
  aksi: "Action",
  adventure: "Adventure",
  petualangan: "Adventure",
  comedy: "Comedy",
  komedi: "Comedy",
  drama: "Drama",
  ecchi: "Ecchi",
  fantasy: "Fantasy",
  fantasi: "Fantasy",
  horror: "Horror",
  horor: "Horror",
  mecha: "Mecha",
  music: "Music",
  musik: "Music",
  mystery: "Mystery",
  misteri: "Mystery",
  psychological: "Psychological",
  psikologis: "Psychological",
  romance: "Romance",
  romansa: "Romance",
  romantis: "Romance",
  "sci-fi": "Sci-Fi",
  scifi: "Sci-Fi",
  "slice of life": "Slice of Life",
  sports: "Sports",
  olahraga: "Sports",
  supernatural: "Supernatural",
  thriller: "Thriller",
  "mahou shoujo": "Mahou Shoujo",
  shounen: "Shounen",
  seinen: "Seinen",
  isekai: "Isekai",
};

export function normalizeGenre(g: string): string {
  if (!g) return "";
  const lower = g.toLowerCase().trim();
  return GENRE_SYNONYMS[lower] || g.trim();
}

export const GENRE_OPTIONS = [
  "Semua",
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Horror",
  "Mecha",
  "Music",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
];
